#!/usr/bin/env python3
"""download_models.py

One-time setup: download all models required for offline operation.

After running this script you can pass  --offline_mode true  to the pipeline
and it will never touch the network.

Usage:
    python download_models.py                          # default ./models dir
    python download_models.py --model-dir /data/models
    python download_models.py --whisper-size medium    # larger ASR model
    python download_models.py --with-pyannote          # needs HF token
    python download_models.py --hf-token hf_xxx --with-pyannote

Models downloaded:
  models/whisper/<size>/      CTranslate2 int8 weights (faster-whisper)
  models/fasttext/lid.176.ftz fastText language-ID model (~900 KB)
  models/diarisation/pyannote/ (optional) pyannote speaker-diarization-3.1
"""
from __future__ import annotations

import argparse
import os
import sys
import urllib.request


# ── fasttext lid.176.ftz ──────────────────────────────────────────────────
FASTTEXT_URL = "https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.ftz"


def _progress_hook(block_num, block_size, total_size):
    downloaded = block_num * block_size
    if total_size > 0:
        pct = min(100, downloaded * 100 // total_size)
        bar = "#" * (pct // 5)
        print(f"\r  [{bar:<20}] {pct}%", end="", flush=True)


def download_fasttext(model_dir: str) -> None:
    dest_dir = os.path.join(model_dir, "fasttext")
    os.makedirs(dest_dir, exist_ok=True)
    dest = os.path.join(dest_dir, "lid.176.ftz")
    if os.path.isfile(dest):
        print(f"  fasttext already present: {dest}")
        return
    print(f"Downloading fasttext lid.176.ftz → {dest}")
    urllib.request.urlretrieve(FASTTEXT_URL, dest, reporthook=_progress_hook)
    print()
    print(f"  saved: {dest} ({os.path.getsize(dest) // 1024} KB)")


# ── faster-whisper (CTranslate2) ─────────────────────────────────────────
def download_whisper(model_dir: str, model_size: str) -> None:
    dest = os.path.join(model_dir, "whisper", model_size)
    # Check for at least one expected weight file.
    if os.path.isfile(os.path.join(dest, "model.bin")):
        print(f"  whisper/{model_size} already present: {dest}")
        return
    print(f"Downloading faster-whisper {model_size} → {dest}")
    try:
        from faster_whisper import WhisperModel
        from huggingface_hub import snapshot_download
    except ImportError as err:
        print(f"  ERROR: {err}")
        print("  Run: pip install faster-whisper huggingface_hub")
        sys.exit(1)

    os.makedirs(dest, exist_ok=True)
    # Download CTranslate2-converted weights from HF.
    hf_repo = f"Systran/faster-whisper-{model_size}"
    print(f"  fetching from HuggingFace: {hf_repo}")
    local = snapshot_download(repo_id=hf_repo, local_dir=dest)
    print(f"  saved: {local}")


# ── pyannote speaker-diarization-3.1 ─────────────────────────────────────
def download_pyannote(model_dir: str, hf_token: str) -> None:
    dest = os.path.join(model_dir, "diarisation", "pyannote")
    config_path = os.path.join(dest, "config.yaml")
    if os.path.isfile(config_path):
        print(f"  pyannote already present: {dest}")
        return
    print(f"Downloading pyannote/speaker-diarization-3.1 → {dest}")
    try:
        from huggingface_hub import snapshot_download
    except ImportError as err:
        print(f"  ERROR: {err}")
        print("  Run: pip install huggingface_hub")
        sys.exit(1)

    os.makedirs(dest, exist_ok=True)
    try:
        local = snapshot_download(
            repo_id="pyannote/speaker-diarization-3.1",
            use_auth_token=hf_token,
            local_dir=dest,
        )
        print(f"  saved: {local}")
    except Exception as err:
        print(f"\n  ERROR downloading pyannote: {err}")
        print(
            "  Make sure you have:\n"
            "    1. A HuggingFace account with access token\n"
            "    2. Accepted terms on https://hf.co/pyannote/speaker-diarization-3.1\n"
            "    3. Accepted terms on https://hf.co/pyannote/segmentation-3.0\n"
            "  Then rerun:  python download_models.py --with-pyannote --hf-token hf_xxx"
        )
        sys.exit(1)


# ── models/ directory README ─────────────────────────────────────────────
def write_readme(model_dir: str) -> None:
    os.makedirs(model_dir, exist_ok=True)
    path = os.path.join(model_dir, "README.txt")
    if os.path.exists(path):
        return
    with open(path, "w") as f:
        f.write(
            "Sonexis model directory\n"
            "=======================\n\n"
            "whisper/<size>/          faster-whisper CTranslate2 weights\n"
            "fasttext/lid.176.ftz    fastText language-ID model\n"
            "diarisation/pyannote/   pyannote speaker-diarization (optional)\n\n"
            "Generated by: python download_models.py\n"
        )


# ── main ─────────────────────────────────────────────────────────────────
def main() -> None:
    p = argparse.ArgumentParser(description="Download models for offline Sonexis pipeline")
    p.add_argument("--model-dir", default=os.environ.get("SONEXIS_MODEL_DIR", "./models"),
                   help="Root directory for model storage (default: ./models)")
    p.add_argument("--whisper-size", default="small",
                   choices=["tiny", "base", "small", "medium", "large-v3"],
                   help="Whisper model size to download (default: small)")
    p.add_argument("--with-pyannote", action="store_true",
                   help="Also download pyannote speaker-diarization model (needs HF token)")
    p.add_argument("--hf-token", default=os.environ.get("HUGGINGFACE_HUB_TOKEN"),
                   help="HuggingFace token (required for --with-pyannote)")
    args = p.parse_args()

    model_dir = os.path.abspath(args.model_dir)
    print(f"Model directory: {model_dir}\n")

    write_readme(model_dir)
    download_fasttext(model_dir)
    download_whisper(model_dir, args.whisper_size)

    if args.with_pyannote:
        if not args.hf_token:
            print(
                "ERROR: --with-pyannote requires a HuggingFace token.\n"
                "  Pass --hf-token hf_xxx  or set HUGGINGFACE_HUB_TOKEN."
            )
            sys.exit(1)
        download_pyannote(model_dir, args.hf_token)

    print(
        f"\nDone. To run the pipeline offline:\n"
        f"  python -m pipeline.main --input ./audio --output ./dataset \\\n"
        f"      --offline_mode true --model-dir {model_dir}"
    )


if __name__ == "__main__":
    main()
